export const CHECKOUT_PRODUCT = 'CHECKOUT_PRODUCT';
export const ADD_ADDRESS = 'ADD_ADDRESS';
export const CHECKOUT_ERROR = 'CHECKOUT_ERROR';
export const APPLY_COUPON = 'APPLY_COUPON';
export const ENABLE_COD = 'ENABLE_COD';
export const REMOVE_SHIPPING_CHARGES = "REMOVE_SHIPPING_CHARGES";
export const REMOVE_COUPON = 'REMOVE_COUPON';