export const MERGE_CART = 'MERGE_CART'
export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const INC_QUANTITY = 'INC_QUANTITY';
export const DEC_QUANTITY = 'DEC_QUANTITY';
export const UPDATE_CART_SUBTOTAL = 'UPDATE_CART_SUBTOTAL';
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';
 