export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER'
export const ADD_NEW_ADDRESS = 'ADD_NEW_ADDRESS';
export const DELETE_ADDRESS = 'DELETE_ADDRESS';
export const UPDATE_EMAIL = 'UPDATE_EMAIL';
export const UPDATE_PERSONAL_INFO ='UPDATE_PERSONAL_INFO'